apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  containers:
  - name: dynamic-pod
    image: nginx:latest
    volumeMounts:
    - name: dynamic-vol
      mountPath: /data/dynamic
  volumes:
  - name: dynamic-vol
    persistentVolumeClaim:
      claimName: dynamic-pvc