apiVersion: v1
kind: Pod
metadata:
  name: static-pod
spec: 
  containers:
  - name: static-pod
    image: nginx:latest
    volumeMounts:
    - name: static-vol
      mountPath: /data
  volumes:
  - name: static-vol
    persistentVolumeClaim:
      claimName: static-pvc
