apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:1.12.2
        ports:
        - containerPort: 80