apiVersion: v1
kind: Pod
metadata:
  name: no-toleration-pod
  labels:
    app: no-toleration
spec:
  containers:
  - name: no-toleration-container
    image: nginx:1.12.2
    ports:
    - containerPort: 80