# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-golang-database-url
  namespace: demo-app
stringData:
  DATABASE_URL: postgres://postgres:root@postgres-postgresql.postgres.svc.cluster.local:5432/postgres
