apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
spec:
  containers:
  - name: foo-app
    image: nginx:1.22.0
    ports:
    - containerPort: 80
  initContainers:
  - name: init-container-1
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']
  - name: init-container-2
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup dbservice.default.svc.cluster.local; do echo waiting for dbservice; sleep 2; done;']    
