apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: multi-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  selector:
    app: multi-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80